### ISSUE TITLE
Separate into individual repos?

### ISSUE THREAD

**Issue by KyleAMathews** [willdady/react-elements#1]
These are great elements! But not very discoverable. Any reason not to break out into separate repos e.g. `react-colorpicker`, `react-mediaobject` etc.?

I'd rather install one of those in one of my projects vs. `react-elements` which I'll probably forget what it is after a few months.

Also it's easier for people to contribute to smaller projects vs. a monolith.

**Comment by willdady** [comment]
@KyleAMathews Thanks for the feedback. It's definitely something I've considered. I plan on waiting until the core React team finalizes the API in a 1.0 release before considering splitting them off. Ultimately I'm waiting to see if there becomes [a 'standard' way of sharing components](https://github.com/facebook/react/issues/676) which also takes care of ancillary assets without the implementer having to mess around with linking in stylesheets or copying images to their site's static directory.

**Comment by KyleAMathews** [comment]
Hmmm fair enough.

Yeah, css/images is the missing piece for components.

I've started loading css for components with the Webpack css-loader, which works wonderfully, but obviously won't work for everyone. An example: https://github.com/KyleAMathews/react-spinkit/blob/master/cjsx/index.cjsx
